# Update User Profile
# PUT http://localhost:3000/api/user/profile/6930063477bdbd4c43e863aa
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "name": "Shakir jamal",
#   "phone": "8675867483",
#   "email": "ameeralivk1875@gmail.com"
# }

# POST http://localhost:3000/api/user/profile/verify-email-otp
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "email": "ameeralivk1875@gmail.com",
#   "otp": "626107"
# }


### Update restaurant image
# PUT http://localhost:3000/api/user/profile/6930063477bdbd4c43e863aa/image
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="profileImage"; filename="pexels-pixabay-414660.jpg"
# Content-Type: image/jpeg

# < ./assets/pexels-pixabay-414660.jpg
# --boundary--

### Get all orders with pagination and search
# POST http://localhost:3000/api/user/orders/695f36345fa15289d991c96c/cancell
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "userId":"6930063477bdbd4c43e863aa"
# }

# GET http://localhost:3000/api/user/wallet
# Content-Type: application/json

# {
#   "userId":"6930063477bdbd4c43e863aa"
# }

# POST http://localhost:3000/api/user/varients
# Content-Type: application/json

# {
#   "name": "Size",
#   "Varients": [
#     { "name": "Half" },
#     { "name": "Full" }
#   ]
# }
# PUT http://localhost:3000/api/user/varients/696c7d88389ac1dcec6c81f8
# Content-Type: application/json

# {
#   "name": "Portion Size",
#   "Varients": [
#     { "name": "Half" },
#     { "name": "Full" },
#     { "name": "Family" }
#   ]
# }

# DELETE  http://localhost:3000/api/user/varients/696c7d88389ac1dcec6c81f8
# Content-Type: application/json


# GET http://localhost:3000/api/user/varients?page=1&limit=5



### Create Feedback
# POST http://localhost:3000/api/user/feedback
# Content-Type: application/json

# {
#   "restaurantId": "60f1a2b3c4d5e6f789012345",
#   "orderId": "65a1b2c3d4e5f67890123419",
#   "itemId": "64f1e2d3c4b5a67890123419",
#   "rating": 1,
#   "comment": "Very tasty"
# }


# GET http://localhost:3000/api/user/feedback/items/692ea36738a54f8d01ed6747

### Update cooking instruction for a cart item
# PATCH http://localhost:3000/api/user/instruction
# Content-Type: application/json

# {
#   "cartId": "69787625b1791ff65437c574",
#   "cartItemId": "696a479aed4aa362e9436b42",
#   "instruction": "Less spicy, extra garlic"
# }


# GET http://localhost:3000/api/staff/getOrders
# Content-Type: application/json


# PATCH  http://localhost:3000/api/staff/update-item
# Content-Type: application/json

# {
#   "orderId": "ORD-20260210-VO51HV",
#   "itemId": "6971d3d1e4b3d201c173bb95",
#   "status": "READY"
# }


### Assign chef using params
### Assign chef to item
# PATCH http://localhost:3000/api/staff/orders/ORD-20260214-IJ4S03/item/694f7c7eb130a027cd281248/assign-cheff
# Content-Type: application/json

# {
#   "chefId": "697ca908cfad78f5aa83d4f7"
# }


# GET http://localhost:3000/api/staff/getAssignedItems/692ea36738a54f8d01ed6747/698dbb06bcc74a177f8719f0
# Content-Type: application/json


### Assign Order to Staff
# PATCH http://localhost:3000/api/staff/assignOrder/ORD-20260216-LDN9O5
# Content-Type: application/json

# {
#   "staffId": "65f1a2b3c4d5e6f7890a1b2c"
# }


### Update order status
# PATCH http://localhost:3000/api/staff/order/updatestatus/ORD-20260217-AJ9JSP
# Content-Type: application/json

# {
#   "status": "SERVED"
# }


# PATCH http://localhost:3000/api/staff/change-password
# Content-Type: application/json

# {
#   "oldPassword": "old123",
#   "newPassword": "new456"
# }

# GET  http://localhost:3000/api/staff/getstaff/698dbb06bcc74a177f8719f0


# GET  http://localhost:3000/api/notification/getNotification/697ca414cfad78f5aa83d4a6

# POST http://localhost:3000/api/user/check-table
# Content-Type: application/json

# {
#   "restaurantId": "692ea36738a54f8d01ed6747",
#   "tableNo": 1
# }

### Staff Login - Test POST
POST http://13.201.130.103/api/admin/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "staff@example.com",
    "password": "yourpassword"
}


















